version: '3.7'

services:

  chrome:
    image: selenium/node-chrome-debug:3.141.59-gold
    ports:
      - 5901:5900
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      SCREEN_WIDTH: 1280
      SCREEN_HEIGHT: 1024

  firefox:
    image: selenium/node-firefox-debug:3.141.59-gold
    ports:
      - 5902:5900
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      SCREEN_WIDTH: 1600
      SCREEN_HEIGHT: 1024

  hub:
    image: selenium/hub:3.141.59-gold
    ports:
      - "4444:4444"
